[build]
  command = "npm run build"
  publish = "out"
[[redirects]]
  from = "https://upbeat-lamport-3c8d2f.netlify.app/"
  to = "https://www.littlebannerlady.com/"
  status = 301
  force = true
[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
